symlinks:
  # Reemplaza los ficheros existentes por enlaces simbolicos
  override: true

  # links simbolicos
  links:
    # kitty terminal
    - ~/.config/kitty/kitty.conf:~/dotfiles/linux/config/kitty/kitty.conf

    # Neofetch
    - ~/.config/neofetch/config.conf:~/dotfiles/share/config/neofetch/config.conf

    # Urxvt terminal
    - ~/.Xresources:~/dotfiles/linux/config/urxvt/Xresources

    # Rofi
    - ~/.config/rofi/config.rasi:~/dotfiles/linux/config/rofi/config.rasi
    - ~/.config/rofi/slate.rasi:~/dotfiles/linux/config/rofi/themes/slate.rasi

    # WM config
    - ~/.config/bspwm/bspwmrc:~/dotfiles/linux/config/bspwm/bspwmrc
    - ~/.config/sxhkd/sxhkdrc:~/dotfiles/linux/config/sxhkd/sxhkdrc
    - ~/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-keyboard-shortcuts.xml:~/dotfiles/linux/config/xfce4/xfconf/xfce-perchannel-xml/xfce4-keyboard-shortcuts.xml
    - ~/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-panel.xml:~/dotfiles/linux/config/xfce4/xfconf/xfce-perchannel-xml/xfce4-panel.xml
    - ~/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-session.xml:~/dotfiles/linux/config/xfce4/xfconf/xfce-perchannel-xml/xfce4-session.xml
    - ~/.config/xfce4/xfconf/xfce-perchannel-xml/xfwm4.xml:~/dotfiles/linux/config/xfce4/xfconf/xfce-perchannel-xml/xfwm4.xml
    - ~/.config/picom/picom.conf:~/dotfiles/linux/config/picom/picom.conf
    - ~/.config/gtk-3.0/gtk.css:~/dotfiles/linux/config/gtk-3.0/gtk.css

    # Themes
    - ~/.themes:~/dotfiles/linux/themes