symlinks:
  # Reemplaza los ficheros existentes por enlaces simbolicos
  override: true

  # links simbolicos
  links:
    # kitty terminal
    - ~/.config/kitty/kitty.conf:~/dotfiles/share/config/kitty/kitty.conf

    # Neofetch
    - ~/.config/neofetch/config.conf:~/dotfiles/linux/config/neofetch/config.conf

    # Urxvt terminal
    - ~/.Xresources:~/dotfiles/linux/config/urxvt/Xresources

    # Rofi
    - ~/.config/rofi/config:~/dotfiles/linux/config/rofi/config